### ISSUE TITLE
P-value threshold

### ISSUE THREAD

**Issue by chadisaad** [bonsai-team/DiNAMO#2]
add P-value threshold parameter ( -t ? ), in place of fixed threshold at 0.05 @debilausaure

**Comment by debilausaure** [comment]
OK, can't add a TODO label though because I am unable to create tags (btw could you please grant me admin rights on this repo ?)

**Comment by debilausaure** [comment]
Implemented, see a9f6ddb9952e45da7f59c564e7f90891533f521d
